### ISSUE TITLE
either not seen, or feature suggest

### ISSUE THREAD

**Issue by robertwerner67** [aureliojargas/txt2regex#8]
For a few days, I use txt2regex (version 0.9) successfully to write regular expressions from the left to the right.  As noticed in expressions written by a colleague, these assertions equally may check of what is written prior to the position initially checked, e.g., the negative look-behind `(?<!e)s` which would identify instances of `s` trailing `i` (like in _fish_), and skip `s` trailing `e` like in _test_.

My question:  are these look-behinds already implemented txt2regex, or maybe foreseen to be implemented in a later version of this very useful program?

**Comment by aureliojargas** [comment]
Hi @robertwerner67,

First of all, I'm sorry for the long time it took me to answer your question.

Look-behind, look-ahead, named groups, non-greedy quantifiers and other modern regex metacharacters are not supported by txt2regex.

Being a "wizard", that tries to be simple and friendly to regex newcomers, it supports only a subset of all the regex power available in the engines.

Those are the supported metacharacters:

    . [] [^] * + ? {} | ()

I'm not opposed to growing that list, but currently there are no plans on doing it.
